### PR TITLE
Styled the leaderboard and game select screen. Added styles folder

### PR DESCRIPTION
**Pull request by Jyro88**

### CODE REVIEW

**Comment by Jyro88** [comment]
image

**Comment by Jyro88** [comment]
image

**Comment by RayyanZaid** [comment]
image
1. One small thing to change. If you look at the UML diagram for the backend (pic above), we have different classes for each leaderboard difficulty. Your mock data should be 3 arrays (one each for Easy, Medium, Hard) because we're not gonna combine all three leaderboards into 1 array in the backend.
image


2. Another thing: I think a better design for this page would be to create an actual leaderboard component since each leaderboard is basically the same thing (like I did for the Round) where you pass in a "name" prop and an "arrayOfPlayers" prop for each leaderboard.

- That way:
- 1. We can choose which leaderboard to display easily (if we only wanna display one at a time)
- 2. It would be extendable to more difficulties or different modes.

**Comment by Jyro88** [comment]
image
New split up leaderboard

**Review by RayyanZaid — APPROVED** [review]
nice, tables look kinda small tho, but we can fix that later

**Pull request merged**
